# Generated by Django 2.2.16 on 2022-06-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220628_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.IntegerField(default=0, verbose_name='Код подтверждения'),
        ),
    ]
