# Generated by Django 2.2.16 on 2022-06-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220629_1402'),
    ]

    operations = [
    ]
