# Generated by Django 2.2.16 on 2022-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220624_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код подтверждения'),
        ),
    ]
