# Generated by Django 2.2.16 on 2022-06-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220628_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
