# Generated by Django 2.2.16 on 2022-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20220628_2359'),
    ]

    operations = [
	migrations.RemoveField(
		model_name='title',
		name='genre',
	),
	migrations.DeleteModel(
            name='Genre_Title',
        ),
	migrations.AddField(
	    model_name='title',
            name='genre',
            field=models.ManyToManyField(to='reviews.Genre', verbose_name='Жанр'),
	),        
    ]
